### ISSUE TITLE
Upper part of the table 1

### ISSUE THREAD

**Issue by nebojsa-bozanic** [deeplearning-wisc/knn-ood#7]
Hi, 

thanks for the great work!

I was able to fully reproduce the lower part of the table 1, with supcon loss (except the random 10k on Places365), however when I use just resnet18 (not resnet18-supcon) I don't get the same results for the upper part of the table. How should I run the cifar10 in order to get the upper part? Do I have to use a different pretrained model which is not uploaded?

Cheers,
n.

**Comment by sunyiyou** [comment]
Hi, the pretrained model is included in the download link https://drive.google.com/file/d/1PJ5SXx0MLvq8kSZ4dmdAJaR77BHz5Y-6/view

See CIFAR-10/resnet18

**Comment by nebojsa-bozanic** [comment]
Thanks!

**Comment by nebojsa-bozanic** [comment]
Thanks. When I use 
```
python feat_extract.py --in-dataset CIFAR-10  --out-datasets SVHN LSUN iSUN dtd places365 --name resnet18-supcon  --model-arch resnet18-supcon
python run_cifar.py --in-dataset CIFAR-10  --out-datasets SVHN LSUN iSUN dtd places365 --name resnet18-supcon  --model-arch resnet18-supcon
```
i get the exact same values as you do in table 1 (except of course places365, but you have explained that it is because you sample random 10000 samples). 
 ```
OOD detection method: KNN k=50
              FPR    AUROC  AUIN  
SVHN           2.42  99.52  99.53
LSUN           1.78  99.48  99.53
iSUN          20.06  96.74  97.63
dtd            8.09  98.56  99.20
```
which matches the table 1 in decimal./
However, when run
```
python feat_extract.py --in-dataset CIFAR-10  --out-datasets SVHN LSUN iSUN dtd places365 --name resnet18  --model-arch resnet18
python run_cifar.py --in-dataset CIFAR-10  --out-datasets SVHN LSUN iSUN dtd places365 --name resnet18  --model-arch resnet18
```
gives
```
              FPR    AUROC  AUIN
SVHN          27.97  95.48  96.23
LSUN          18.50  96.84  97.18
iSUN          24.68  95.52  96.35
dtd           26.74  94.96  97.05
```
which is different than what table 1 shows. Is there some logical explanation why it gives the same results to the decimal in the first case, and not in the second?

**Comment by sunyiyou** [comment]
Interesting. I just tried it on my local machine. The results are consistent with yours. 

     FPR    AUROC  AUIN  
SVHN          27.97  95.48  96.23
LSUN          18.50  96.84  97.18
iSUN          24.68  95.52  96.35
dtd           26.74  94.96  97.05
places365     47.84  89.93  89.85
AVG           29.15  94.55  95.33

In paper, we have averaged FPR 30.77 AUROC 94.15, which looks similar. 

I also checked the in-distribution accuracy. The number 94.21 matches. So the checkpoint should be also the same one. 

Then the difference of the 1% gap in FPR can come from some minor changes in the evaluation setting. e.g. 1) the mean/std used in the image normalization. 2) if the augmentation is used for computing the training images' embeddings. 

I lost track of what is the exact code version used in paper (KNN with CE loss). But since the gap is small, you can safely use either one as a baseline to compare with.

**Comment by nebojsa-bozanic** [comment]
Thanks for the prompt response.
Cheers!
